name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4

      with:
        python-version: '3.10'  # Replace with your Python version

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Replace with your AWS region

    - name: Upload to S3
      run: |
        zip -r app.zip .
        aws s3 cp app.zip s3://flask-app-deployment/app.zip --debug

      - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name Flask-Personal-Blog \
          --version-label v1.0.${{ github.run_number }} \
          --source-bundle S3Bucket=flask-app-deployment,S3Key=app.zip
        
        aws elasticbeanstalk update-environment \
          --application-name Flask-Personal-Blog \
          --environment-name Flask-Personal-Blog-env \
          --version-label v1.0.${{ github.run_number }}